VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
MAGIC_ENABLE = no
TAP_DANCE_ENABLE = no

COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
AUDIO_ENABLE = no
CONSOLE_ENABLE = no